### PR TITLE
Support hyperlink such as "1.http://", and improve readality

### PR DESCRIPTION
**Pull request by zzz0072**
The original design can not handle hyperlink with valid scheme
characters before the real scheme, such as "1.http://".

This implementation is to
1. Extract valid scheme from those case mentioned above
2. Stop URL detection immediately at a line if there is no "://" in it
3. Use macro instead of hardcode in URL detection

### CODE REVIEW

**Comment by zzz0072** [comment]
Fixed the unused variable

**Comment by kidwm** [comment]
@zzz0072 could you do a rebase and squash commits?

**Comment by zzz0072** [comment]
Can you provide more details? I am not familiar with rebase and squash. Thanks very much!

**Comment by hwangcc23** [comment]
@zzz0072,
You can google "git squash" or reference https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/

**Comment by cmchao** [comment]
This reference may be helpful for rebase and squash
https://blog.yorkxin.org/posts/2011/07/29/git-rebase/

**Comment by zzz0072** [comment]
Thanks for your information. I just wonder what is expected (what will be) before and after git rebase and squash? So that I can confirm my action/command is correct or not. Thank again.

**Comment by zzz0072** [comment]
done. Please review again. Thanks!

**Pull request merged**
