### PR TITLE
Rename README to README.md

### PR DESCRIPTION
**Pull request by PeterDaveHello**
So GitHub will parse the syntax like https://github.com/pcman-bbs/pcmanx/blob/master/README#L2, and we could put something more, like travis-ci badge to know the build status easily.

### CODE REVIEW

**Comment by kidwm** [comment]
這要問問其他人的意見，我是不反對
@czchen 如何？

**Comment by czchen** [comment]
Fine with me, but please help to fix build error caused by this PR before merging.

**Comment by kidwm** [comment]
弄個 symbolic link 應該就可以避開了？

**Comment by PeterDaveHello** [comment]
Done :+1:

**Pull request merged**
