### PR TITLE
fix gtk_pixbuf bug

### PR DESCRIPTION
**Pull request by kunhuahuang**
Have patch!!
Avoid the initial prooblem. Fix gtk pixbuf and gdk pixbuf bug. 

When first run in shell. There are some warning:
-------------------------------------------------------------------------------------------------------------------

(pcmanx:3853): Gtk-CRITICAL **: IA__gtk_image_get_pixbuf: assertion 'image->storage_type == GTK_IMAGE_PIXBUF || image->sto
rage_type == GTK_IMAGE_EMPTY' failed

(pcmanx:3853): GdkPixbuf-CRITICAL **: gdk_pixbuf_scale_simple: assertion 'GDK_IS_PIXBUF (src)' failed

(pcmanx:3853): GdkPixbuf-CRITICAL **: gdk_pixbuf_copy: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(pcmanx:3853): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_n_channels: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(pcmanx:3853): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_rowstride: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(pcmanx:3853): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_width: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(pcmanx:3853): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_height: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(pcmanx:3853): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_pixels: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(pcmanx:3853): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

----------------------------------------------------------------------------------------------------------------------------------------

This patch can fix these problem.

### CODE REVIEW

**Comment by RudyChin** [comment]
Works well!

**Comment by tnlin** [comment]
It works(No error msg), but the icon is still  a  question mark
a

**Comment by kunhuahuang** [comment]
Hi tnlin~ Your problem is because the program cannot find the pcmanx icon. 
The icon is in the source code path of pcmanx/data/pcmanx.svg. 
If you trace the code, the DATADIR path must be at  /usr/share/
Because you do not install the program, so the program icon is never add into your system.
Of course, the program cannot find the icon. 
Please put this  "pcmanx.svg" file into  /usr/share/pixmaps/
Then, you will find the icon is successfully show up.

**Comment by tnlin** [comment]
kunhuahuang: I see , thanks a lot!

**Comment by jserv** [comment]
Merged in commit a0107054ee74a441876202a26611e27ead8ffb83

**Pull request closed without merging**
