### PR TITLE
Shrink the title of an opened tab

### PR DESCRIPTION
**Pull request by mhwong2007**
If the title of an opened tab is too long, it will not be shown
within a tab. Instead, it shows all the characters of the title
and messes with the other tab title. Please see the following
picture for a better problem description.

http://i.imgur.com/MPPosvb.png

This commit first checks if the the length of a title is longer
than 20 characters. If so, it will shrink the title into 17
characters and add '...' at the end, 20 characters in total.

http://i.imgur.com/k8VggEN.png

### CODE REVIEW

**Comment by mhwong2007** [comment]
@jserv I created a new branch "shrink_tab_title" and sent a pull request. Please review.

**Comment by jserv** [comment]
It looks weird. I suppose that you should rebase to pcmanx/master branch. Please re-do.

**Comment by mhwong2007** [comment]
@jserv I rebased to pcmanx/master branch. Please review.

**Comment by jserv** [comment]
Looks good. Merged.

Thanks again for your contribution.

**Pull request closed without merging**
