### PR TITLE
Add checking function on autogen.sh and view/telnetcon.cpp to support mac os.

### PR DESCRIPTION
**Pull request by cychiang**
I face a problem when I try to build "pcmanx" on my macbook, but now is ok. Here is my result, add checking function on autogen.sh and view/telnetcon.cpp.

### CODE REVIEW

**Comment by dimotsai** [comment]
@cychiang I found [a syntax error](https://github.com/pcman-bbs/pcmanx/pull/24/files#diff-e41c4fc3ba3ae5d2a83d5c3138415c6dR90) in your commit.
```
#ifdef __APPLE__ && __MACH__
```
The second token `__MACH__` won't be evaluated by cpp
Please refer:
1. http://stackoverflow.com/questions/1312132/booleans-inside-ifdef-statements
2. https://gist.github.com/dimotsai/73d755f409340bfca99f
3. https://gcc.gnu.org/onlinedocs/gcc-4.9.2/cpp/Defined.html#Defined

**Comment by cychiang** [comment]
Hi @dimotsai : 
Thank you for your report. The problem seem to be occurring in different version of compiler. Because this macro work fine on mac yosemite with g++ 4.2.1. Could you kindly specify your compiler version and OS environment? It will be good to locate the problem.

**Comment by dimotsai** [comment]
My current environment is OSX 10.10.2 Yosemite. In fact, pcmanx works fine without any problems since my compiler(clang-600.0.56) simply ignore the statement after `__APPLE__`(where `__APPLE__` is already been defined). But I don't see any warning messages when building pcmanx.

Besides, `g++-4.2.1` give the same result (x==3) on [this program](https://gist.github.com/dimotsai/73d755f409340bfca99f). `clang` and `g++-4.9.2` do have warnings when compiling, but I don't see any warning or error on g++-4.2.1 until I add an option `-Wextra-tokens`.

On clang:
```
ifdef.cpp:6:14: warning: extra tokens at end of #ifdef directive [-Wextra-tokens]
#ifdef FIRST && SECOND
             ^
             //
1 warning generated.
```

**Comment by cychiang** [comment]
@dimotsai 
First, I am grateful for your help and demonstrate so much detail of this potential syntax problem. I will fix this potential compiler risk as soon as possible.
I learn a lot from you. Thanks again.

**Comment by dimotsai** [comment]
@cychiang Thanks for your help :smile_cat:

**Pull request merged**
