### PR TITLE
Strip the title if its length is larger than 20 characters.

### PR DESCRIPTION
**Pull request by mhwong2007**
If the title of an opened tab is too long, it will not be shown
within a tab. Instead, it shows all the characters of the title
and mess with the other tab title. Please see the following
picture for a better problem description.

http://i.imgur.com/MPPosvb.png

This commit first checks if the the length of a title is longer
than 20 characters. If so, it will shrink the title into 17
characters and add '...' at the end, 20 characters in total.

http://i.imgur.com/k8VggEN.png

### CODE REVIEW

**Comment by jserv** [comment]
Any chance to rework this patch?

**Comment by jserv** [comment]
We usually call it "shrink" rather than "strip" for string manipulations.

**Comment by mhwong2007** [comment]
@jserv Thanks! I can't recall the term "shrink" that day I sent this pull request. Will improve the commit message and send request again.

**Comment by jserv** [comment]
You can always use `git commit --amend` to modify your commits.
Please check "git commit --help".

**Comment by mhwong2007** [comment]
@jserv I changed the commit message. Please review.

**Comment by jserv** [comment]
Can you create a new GIT branch and send pull request again. Otherwise, the old GIT commits confuse me.

**Pull request closed without merging**
